// Mocks generated by Mockito 5.4.6 from annotations
// in walkie_talkie/test/bloc/discovery_cubit_test.dart.
// Do not manually edit this file.
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:walkie_talkie/protocol/discovery.dart' as _i4;
import 'package:walkie_talkie/services/bluetooth_discovery_service.dart'
    as _i2;

class MockDiscoveryService extends _i1.Mock implements _i2.DiscoveryService {
  MockDiscoveryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.DiscoveredSession>> get results => (super.noSuchMethod(
        Invocation.getter(#results),
        returnValue: _i3.Stream<List<_i4.DiscoveredSession>>.empty(),
      ) as _i3.Stream<List<_i4.DiscoveredSession>>);

  @override
  _i3.Future<void> startScan() => (super.noSuchMethod(
        Invocation.method(
          #startScan,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopScan() => (super.noSuchMethod(
        Invocation.method(
          #stopScan,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
