// Mocks generated by Mockito 5.4.6 from annotations
// in walkie_talkie/test/bloc/discovery_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_blue_plus/flutter_blue_plus.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:walkie_talkie/protocol/discovery.dart' as _i4;
import 'package:walkie_talkie/services/bluetooth_discovery_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DiscoveryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoveryService extends _i1.Mock implements _i2.DiscoveryService {
  MockDiscoveryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.DiscoveredSession>> get results =>
      (super.noSuchMethod(
            Invocation.getter(#results),
            returnValue: _i3.Stream<List<_i4.DiscoveredSession>>.empty(),
          )
          as _i3.Stream<List<_i4.DiscoveredSession>>);

  @override
  _i3.Future<void> startScan() =>
      (super.noSuchMethod(
            Invocation.method(#startScan, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopScan() =>
      (super.noSuchMethod(
            Invocation.method(#stopScan, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i4.DiscoveredSession? parseResult(_i5.ScanResult? r) =>
      (super.noSuchMethod(Invocation.method(#parseResult, [r]))
          as _i4.DiscoveredSession?);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
