name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: flutter   # ghcr.io/cirruslabs/flutter:stable
    steps:
      - uses: actions/checkout@v4
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
